authors:
  - Valentin Oliver Loftsson <valentin@hestia.ai>
  - Florian Singer <florian.singer@hestia.ai>

prefixes:
  ex: http://www.example.com/
  schema: http://schema.org/

sources:
  imp-impressions:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*]
  eng-impressions:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes

mappings:
  advertiser:
    sources:
      - imp-impressions
      - eng-impressions
    s: schema:Organization/$(advertiserInfo.screenName)
    po:
      - [a, schema:Organization]
      - [schema:name, $(advertiserInfo.advertiserName)]
      - [schema:alternateName, $(advertiserInfo.screenName)]
  impressions:
    sources:
      - imp-impressions
    # Impressions are identified with the screenName + impressionTime
    s: ex:Impression/$(advertiserInfo.screenName)/$(impressionTime)
    po:
      - [a, ex:Impression]
      - p: ex:Advertiser
        o:
          mapping: advertiser
          condition:
            function: equal
            parameters:
              - [str1, $(advertiserInfo.screenName), s]
              - [str2, $(advertiserInfo.screenName), o]
  engagements:
    sources:
      - eng-impressions
    # Engagements are identified with the screenName + impressionTime
    s: ex:Engagement/$(advertiserInfo.screenName)/$(impressionTime)
    po:
      - [a, ex:Engagement]
      - p: ex:Advertiser
        o:
          mapping: advertiser
          condition:
            function: equal
            parameters:
              - [str1, $(advertiserInfo.screenName), s]
              - [str2, $(advertiserInfo.screenName), o]
