prefixes:
  h: http://hestia.ai/
  ex: http://www.example.com/

sources:
  off_facebook_activity:
    access: apps_and_websites_off_of_facebook/your_off-facebook_activity.json
    referenceFormulation: jsonpath
    iterator: $.off_facebook_activity_v2[*].events[*]
  your_topics:
    access: your_topics/your_topics.json
    referenceFormulation: jsonpath
    iterator: $.inferred_topics_v2[*]
  ad_interactions:
    access: ads_information/advertisers_you've_interacted_with.json
    referenceFormulation: jsonpath
    iterator: $.history_v2[*]
  advertisers_contact_list:
    access: ads_information/advertisers_who_uploaded_a_contact_list_with_your_information.json
    referenceFormulation: jsonpath
    iterator: $.custom_audiences_v2[*]

mappings:
  activity:
    sources:
      - off_facebook_activity
    s: h:off_facebook_activity/$(^^.name)/$(timestamp)
    po:
      - [a, h:off_facebook_activity]
      - [h:app_name, $(^^.name)]
      - [h:timestamp, $(timestamp)]
      - [h:id, $(id)]
      - [h:type, $(type)]
  topics:
    sources:
      - your_topics
    s: h:topic/$(topic)
    po:
      - [a, h:topic]
      - [h:value, $(topic)]
  interactions:
    sources:
      - ad_interactions
    s: h:interaction/$(timestamp)
    po:
      - [a, h:interaction]
      - [h:title, $(title)]
      - [h:action, $(action)]
      - [h:timestamp, $(timestamp)]
  advertisers:
    sources:
      - advertisers_contact_list
    s: h:advertiser_contact_list/$(advertiser)
    po:
      - [a, h:advertiser_contact_list]
      - [h:value, $(advertiser)]
