authors: Valentin Oliver Loftsson <valentin@hestia.ai>

prefixes:
  ex: http://www.example.com/
  h: http://hestia.ai/

sources:
  imp-criteria:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*].matchedTargetingCriteria[*]

mappings:
  criterion:
    sources:
      - imp-criteria
    po:
      - [a, h:Criterion]
      - [h:type, $(targetingType)]
      - [h:value, $(targetingValue)]
      - [h:advertiser, $(^^.advertiserInfo.screenName)]
      - p: h:time
        o:
          function: ex:dateTimeAddTimeChar
          parameters:
            - [ex:input, $(^^.impressionTime)]
          datatype: xsd:dateTime
