prefixes:
  h: http://hestia.ai/
  ex: http://www.example.com/

sources:
  imp-impressions:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*]
  eng-impressions:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes
  imp-criteria:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*].matchedTargetingCriteria[*]
  eng-criteria:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes.matchedTargetingCriteria[*]

mappings:
  impression:
    sources:
      - imp-impressions
    s: h:Impression/$(advertiserInfo.screenName)/$(impressionTime)
    po:
      - [a, h:Impression]
      - [h:advertiserName, $(advertiserInfo.advertiserName)]
      - [h:tweetId, $(promotedTweetInfo.tweetId)]
      - [h:impressionTime, $(impressionTime)]
      - [h:engagement, 'false', xsd:boolean]
  engagement:
    sources:
      - eng-impressions
    s: h:Engagement/$(advertiserInfo.screenName)/$(impressionTime)
    po:
      - [a, h:Engagement]
      - [h:advertiserName, $(advertiserInfo.advertiserName)]
      - [h:tweetId, $(promotedTweetInfo.tweetId)]
      - [h:impressionTime, $(impressionTime)]
      - [h:engagement, 'true', xsd:boolean]
  imp-criterion:
    sources:
      - imp-criteria
    s: h:Criterion/$(targetingType)/$(targetingValue)/$(^^.advertiserInfo.screenName)/$(^^.impressionTime)
    po:
      - [a, h:Criterion]
      - [h:targetingType, $(targetingType)]
      - [h:targetingValue, $(targetingValue)]
      - p: h:impression
        o:
          mapping: impression
          condition:
            - function: equal
              parameters:
                - [str1, $(^^.advertiserInfo.screenName), s]
                - [str2, $(advertiserInfo.screenName), o]
            - function: equal
              parameters:
                - [str1, $(^^.impressionTime), s]
                - [str2, $(impressionTime), o]
  eng-criterion:
    sources:
      - eng-criteria
    s: h:Criterion/$(targetingType)/$(targetingValue)/$(^^.advertiserInfo.screenName)/$(^^.impressionTime)
    po:
      - [a, h:Criterion]
      - [h:targetingType, $(targetingType)]
      - [h:targetingValue, $(targetingValue)]
      - p: h:engagement
        o:
          mapping: engagement
          condition:
            - function: equal
              parameters:
                - [str1, $(^^.advertiserInfo.screenName), s]
                - [str2, $(advertiserInfo.screenName), o]
            - function: equal
              parameters:
                - [str1, $(^^.impressionTime), s]
                - [str2, $(impressionTime), o]
