prefixes:
  h: http://hestia.ai/
  ex: http://www.example.com/

sources:
  imp-impressions:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*]
  imp-criteria:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*].matchedTargetingCriteria[*]
  eng-criteria:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes.matchedTargetingCriteria[*]

mappings:
  impression:
    sources:
      - imp-impressions
    s: h:Impression/$(advertiserInfo.screenName)/$(impressionTime)
    po:
      - [a, h:Impression]
      - [h:advertiserName, $(advertiserInfo.advertiserName)]
      - p: h:impressionTime
        o:
          function: ex:dateTimeAddTimeChar
          parameters:
            - [ex:input, $(impressionTime)]
          datatype: xsd:dateTime
  imp-criterion:
    sources:
      - imp-criteria
    s: h:Criterion/$(targetingType)/$(targetingValue)/$(^^.advertiserInfo.screenName)/$(^^.impressionTime)
    po:
      - [a, h:Criterion]
      - [h:targetingType, $(targetingType)]
      - [h:targetingValue, $(targetingValue)]
      - [h:advertiserName, $(^^.advertiserInfo.advertiserName)]
      - [h:tweetId, $(^^.promotedTweetInfo.tweetId)]
      - [h:impressionTime, $(^^.impressionTime)]
      - [h:engagement, 'false', xsd:boolean]
  eng-criterion:
    sources:
      - eng-criteria
    s: h:Criterion/$(targetingType)/$(targetingValue)/$(^^.advertiserInfo.screenName)/$(^^.impressionTime)
    po:
      - [a, h:Criterion]
      - [h:targetingType, $(targetingType)]
      - [h:targetingValue, $(targetingValue)]
      - [h:advertiserName, $(^^.advertiserInfo.advertiserName)]
      - [h:tweetId, $(^^.promotedTweetInfo.tweetId)]
      - [h:impressionTime, $(^^.impressionTime)]
      - [h:engagement, 'true', xsd:boolean]
