authors: Valentin Oliver Loftsson <valentin@hestia.ai>

prefixes:
  ex: http://www.example.com/
  schema: http://schema.org/

sources:
  imp-impressions:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*]
  eng-impressions:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes
  eng-engagements:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].engagementAttributes[*]
  imp-criteria:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*].matchedTargetingCriteria[*]
  eng-criteria:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes.matchedTargetingCriteria[*]

mappings:
  # advertiser info
  advertiser:
    sources:
      - imp-impressions
      - eng-impressions
    s: schema:Organization/$(advertiserInfo.screenName)
    po:
      - [a, schema:Organization]
      - [schema:name, $(advertiserInfo.advertiserName)]
      - [schema:alternateName, $(advertiserInfo.screenName)]

  # trends
  trend:
    sources:
      - imp-impressions
      - eng-impressions
    s: schema:Thing/trend/$(promotedTrendInfo.trendId)
    po:
      - [a, schema:Thing]
      - [schema:identifier, $(promotedTrendInfo.trendId)]
      - [schema:name, $(promotedTrendInfo.name)]
      - [schema:description, $(promotedTrendInfo.description)]

  # ad impression
  impression:
    sources:
      - imp-impressions
      - eng-impressions
    s: schema:AdvertiserContentArticle/advertiser/$(advertiserInfo.screenName)/time/$(impressionTime)
    po:
      - [a, schema:AdvertiserContentArticle]
      - [schema:actionPlatform, $(deviceInfo.osType)]
      - [ex:displayLocation, $(displayLocation)]
      - [schema:articleBody, $(promotedTweetInfo.tweetText)]
      - [schema:identifier, $(promotedTweetInfo.tweetId)]
      - [ex:urls, $(promotedTweetInfo.urls)]
      - [ex:mediaUrls, $(promotedTweetInfo.mediaUrls)]
      - p: schema:about
        o:
          mapping: trend
          condition:
            function: equal
            parameters:
              - [str1, $(promotedTrendInfo.trendId), s]
              - [str2, $(promotedTrendInfo.trendId), o]
      - p: schema:creator
        o:
          mapping: advertiser
          condition:
            function: equal
            parameters:
              - [str1, $(advertiserInfo.screenName), s]
              - [str2, $(advertiserInfo.screenName), o]
      - p: schema:contentReferenceTime
        o:
          function: ex:dateTimeAddTimeChar
          parameters:
            - [ex:input, $(impressionTime)]
          datatype: xsd:dateTime

  # ad engagement
  engagement:
    sources:
      - eng-engagements
    po:
      - [a, schema:Action]
      - [schema:name, $(engagementType)]
      - p: schema:object
        o:
          mapping: impression
          condition:
            function: equal
            parameters:
              - [str1, $(^^.impressionAttributes.impressionTime)]
              - [str2, $(impressionTime)]
      - p: schema:endTime
        o:
          function: ex:dateTimeAddTimeChar
          parameters:
            - [ex:input, $(engagementTime)]
          datatype: xsd:dateTime

  # matched targeting criteria
  targetingType:
    sources:
      - imp-criteria
      - eng-criteria
    s: schema:Enumeration/targetingType/$(targetingType)
    po:
      - [a, schema:Enumeration]
      - [schema:name, $(targetingType)]

  targetingValue:
    sources:
      - imp-criteria
      - eng-criteria
    s: schema:PropertyValue/targetingValue/$(targetingValue)
    po:
      - [a, schema:PropertyValue]
      - [schema:value, $(targetingValue)]
      - p: schema:valueReference
        o:
          mapping: targetingType
          condition:
            function: equal
            parameters:
              - [str1, $(targetingType), s]
              - [str2, $(targetingType), o]

      # rdf:Bag not supported so needed to do this instead
      # of linking an impression to its targetingValues
      - p: schema:subjectOf
        o:
          mapping: impression
          condition:
            function: equal
            parameters:
              - [str1, $(^^.impressionTime), s]
              - [str2, $(impressionTime), o]
