authors: Valentin Oliver Loftsson <valentin@hestia.ai>

prefixes:
  ex: http://www.example.com/
  schema: http://schema.org/

sources:
  imp-impressions:
    access: data/ad-impressions.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adImpressions.impressions[*]
  eng-impressions:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].impressionAttributes
  eng-engagements:
    access: data/ad-engagements.js
    referenceFormulation: jsonpath
    iterator: $.*.ad.adsUserData.adEngagements.engagements[*].engagementAttributes[*]

mappings:
  # advertiser info
  advertiser:
    sources:
      - imp-impressions
      - eng-impressions
    s: schema:Organization/$(advertiserInfo.screenName)
    po:
      - [a, schema:Organization]
      - [schema:name, $(advertiserInfo.advertiserName)]
      - [schema:alternateName, $(advertiserInfo.screenName)]

  # ad impression
  impression:
    sources:
      - imp-impressions
      - eng-impressions
    s: schema:AdvertiserContentArticle/advertiser/$(advertiserInfo.screenName)/time/$(impressionTime)
    po:
      - [a, schema:AdvertiserContentArticle]
      - [schema:actionPlatform, $(deviceInfo.osType)]
      - [ex:displayLocation, $(displayLocation)]
      - [schema:articleBody, $(promotedTweetInfo.tweetText)]
      - [schema:identifier, $(promotedTweetInfo.tweetId)]
      - [ex:urls, $(promotedTweetInfo.urls)]
      - [ex:mediaUrls, $(promotedTweetInfo.mediaUrls)]
      # https://github.com/hestiaAI/hestia-rml-demo/issues/46
      # - [ex:promotedTrend, $(promotedTrendInfo)]
      # - [ex:targetingCriteria, $(matchedTargetingCriteria)]
      - p: schema:creator
        o:
          mapping: advertiser
          condition:
            function: equal
            parameters:
              - [str1, $(advertiserInfo.screenName), s]
              - [str2, $(advertiserInfo.screenName), o]
      - p: schema:contentReferenceTime
        o:
          function: ex:dateTimeAddTimeChar
          parameters:
            - [ex:input, $(impressionTime)]
          datatype: xsd:dateTime

  # ad engagement
  engagement:
    sources:
      - eng-engagements
    po:
      - [a, schema:Action]
      - [schema:name, $(engagementType)]
      - p: schema:object
        o:
          mapping: impression
          condition:
            function: equal
            parameters:
              - [str1, $(^^.impressionAttributes.impressionTime)]
              - [str2, $(impressionTime)]
      - p: schema:endTime
        o:
          function: ex:dateTimeAddTimeChar
          parameters:
            - [ex:input, $(engagementTime)]
          datatype: xsd:dateTime
